### ISSUE TITLE
Make the bluetooth detection code a library, move it to contact-tracing-bluetooth-kotlin repo

### ISSUE THREAD

**Issue by freyley** [covid19risk/covidwatch-android#10]
Move code in `libcontactrace` module to a separate repo.

## TODO:
- [x] Create a separate branch for changes 
- [x] Use `org.covidwatch.contactracing` package for the library
- [x] Copy all the files from `libcontactrace` module
- [x] Create `develop` branch in the `contact-tracing-bluetooth-kotlin` repo
- [x] Remove `libcontactrace` module 
- [x] Add `contact-tracing-bluetooth-kotlin`  library using https://jitpack.io/

**Comment by Apisov** [comment]
After some discussion and changes in the organization it was decided to move the code to [TCN Coalization](https://github.com/TCNCoalition) organization repo. 
@zssz first test if the `libcen` branch works before proceeding.
