### ISSUE TITLE
Clean Gradle files

### ISSUE THREAD

**Issue by Apisov** [covid19risk/covidwatch-android#117]
## TODO
- [ ] Use separate variable for versions
- [ ] Clean commented code

### Bonus
- [ ] Perhaps use Kotlin instead of Groovy
